server:
  port: 8761
eureka:
  client:
    register-with-eureka: false #是否将自己注册到 Eureka-Server 中，默认的为 true
    fetch-registry: false #是否需要拉取服务信息，默认为true
  server:
    number-of-replication-retries: 1
  instance:
    prefer-ip-address: false
    hostname: eureka-server